### ISSUE TITLE
Equation referencing doesn't work properly

### ISSUE THREAD

**Issue by kalmant** [Venemo/bme-vik-dipterv-latex-sablon#1]
Referencing equations doesn't work as intended.
Proposed fix: in diploma.tex change `\usepackage[thmmarks]{ntheorem}` to `\usepackage[thmmarks,amsmath]{ntheorem}`

**Comment by Venemo** [comment]
Please check if the fix works and let me know.

**Comment by kalmant** [comment]
It does work, thanks!
